// <auto-generated />
using InscripcionWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InscripcionWeb.Migrations
{
    [DbContext(typeof(InscripcionWebContext))]
    [Migration("20210623152933_DatosSemilla")]
    partial class DatosSemilla
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InscripcionWeb.Models.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Telefono")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Alumnos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Valle",
                            Dni = 37454714,
                            Eliminado = false,
                            Email = "ivanvallesj@gmail.com",
                            Nombre = "Carlos Ivan ",
                            Telefono = 3498459297.0
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Colombo",
                            Dni = 38584798,
                            Eliminado = false,
                            Email = "juancolombosj@gmail.com",
                            Nombre = "Juan Pablo ",
                            Telefono = 3498459299.0
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Córdoba",
                            Dni = 38957452,
                            Eliminado = false,
                            Email = "rami@gmail.com",
                            Nombre = "Ramiro ",
                            Telefono = 3498459298.0
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "Sabino",
                            Dni = 39625852,
                            Eliminado = false,
                            Email = "mati@gmail.com",
                            Nombre = "Matias ",
                            Telefono = 3498459295.0
                        },
                        new
                        {
                            Id = 5,
                            Apellido = "Mangini",
                            Dni = 37154825,
                            Eliminado = false,
                            Email = "jere@gmail.com",
                            Nombre = "Jeremias  ",
                            Telefono = 3498459294.0
                        },
                        new
                        {
                            Id = 6,
                            Apellido = " Paulon ",
                            Dni = 37124896,
                            Eliminado = false,
                            Email = "corado@gmail.com",
                            Nombre = "Conrado",
                            Telefono = 3498459293.0
                        },
                        new
                        {
                            Id = 7,
                            Apellido = " Gomez ",
                            Dni = 38957412,
                            Eliminado = false,
                            Email = "nahuel@gmail.com",
                            Nombre = "Nahuel",
                            Telefono = 3498459292.0
                        },
                        new
                        {
                            Id = 8,
                            Apellido = " Barreto",
                            Dni = 39658745,
                            Eliminado = false,
                            Email = "santi@gmail.com",
                            Nombre = "Santiago",
                            Telefono = 3498459291.0
                        });
                });

            modelBuilder.Entity("InscripcionWeb.Models.AñoCursado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.ToTable("AñoCursados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarreraId = 1,
                            Eliminado = false,
                            Nombre = "Primero"
                        },
                        new
                        {
                            Id = 2,
                            CarreraId = 1,
                            Eliminado = false,
                            Nombre = "Segundo"
                        },
                        new
                        {
                            Id = 3,
                            CarreraId = 1,
                            Eliminado = false,
                            Nombre = "Tercero"
                        },
                        new
                        {
                            Id = 4,
                            CarreraId = 2,
                            Eliminado = false,
                            Nombre = "Primero"
                        },
                        new
                        {
                            Id = 5,
                            CarreraId = 2,
                            Eliminado = false,
                            Nombre = "Segundo"
                        },
                        new
                        {
                            Id = 6,
                            CarreraId = 2,
                            Eliminado = false,
                            Nombre = "Tercero"
                        },
                        new
                        {
                            Id = 7,
                            CarreraId = 3,
                            Eliminado = false,
                            Nombre = "Primero"
                        },
                        new
                        {
                            Id = 8,
                            CarreraId = 3,
                            Eliminado = false,
                            Nombre = "Segundo"
                        },
                        new
                        {
                            Id = 9,
                            CarreraId = 3,
                            Eliminado = false,
                            Nombre = "Tercero"
                        },
                        new
                        {
                            Id = 10,
                            CarreraId = 4,
                            Eliminado = false,
                            Nombre = "Primero"
                        },
                        new
                        {
                            Id = 11,
                            CarreraId = 4,
                            Eliminado = false,
                            Nombre = "Segundo"
                        },
                        new
                        {
                            Id = 12,
                            CarreraId = 4,
                            Eliminado = false,
                            Nombre = "Tercero"
                        },
                        new
                        {
                            Id = 13,
                            CarreraId = 5,
                            Eliminado = false,
                            Nombre = "Primero"
                        },
                        new
                        {
                            Id = 14,
                            CarreraId = 5,
                            Eliminado = false,
                            Nombre = "Segundo"
                        },
                        new
                        {
                            Id = 15,
                            CarreraId = 5,
                            Eliminado = false,
                            Nombre = "Tercero"
                        },
                        new
                        {
                            Id = 16,
                            CarreraId = 5,
                            Eliminado = false,
                            Nombre = "Cuarto"
                        },
                        new
                        {
                            Id = 17,
                            CarreraId = 6,
                            Eliminado = false,
                            Nombre = "Primero"
                        },
                        new
                        {
                            Id = 18,
                            CarreraId = 6,
                            Eliminado = false,
                            Nombre = "Segundo"
                        },
                        new
                        {
                            Id = 19,
                            CarreraId = 6,
                            Eliminado = false,
                            Nombre = "Tercero"
                        },
                        new
                        {
                            Id = 20,
                            CarreraId = 6,
                            Eliminado = false,
                            Nombre = "Cuarto"
                        },
                        new
                        {
                            Id = 21,
                            CarreraId = 7,
                            Eliminado = false,
                            Nombre = "Primero"
                        },
                        new
                        {
                            Id = 22,
                            CarreraId = 7,
                            Eliminado = false,
                            Nombre = "Segundo"
                        },
                        new
                        {
                            Id = 23,
                            CarreraId = 7,
                            Eliminado = false,
                            Nombre = "Tercero"
                        },
                        new
                        {
                            Id = 24,
                            CarreraId = 7,
                            Eliminado = false,
                            Nombre = "Cuarto"
                        },
                        new
                        {
                            Id = 25,
                            CarreraId = 8,
                            Eliminado = false,
                            Nombre = "Primero"
                        },
                        new
                        {
                            Id = 26,
                            CarreraId = 8,
                            Eliminado = false,
                            Nombre = "Segundo"
                        },
                        new
                        {
                            Id = 27,
                            CarreraId = 8,
                            Eliminado = false,
                            Nombre = "Tercero"
                        },
                        new
                        {
                            Id = 28,
                            CarreraId = 8,
                            Eliminado = false,
                            Nombre = "Cuarto"
                        },
                        new
                        {
                            Id = 29,
                            CarreraId = 9,
                            Eliminado = false,
                            Nombre = "Primero"
                        });
                });

            modelBuilder.Entity("InscripcionWeb.Models.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carreras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Eliminado = false,
                            Nombre = "Tecnicatura Superior en Desarrollo de Software"
                        },
                        new
                        {
                            Id = 2,
                            Eliminado = false,
                            Nombre = "Tecnicatura Superior en Soporte de Infraestructura"
                        },
                        new
                        {
                            Id = 3,
                            Eliminado = false,
                            Nombre = "Tecnicatura Superior en Gestion de las Organizaciones"
                        },
                        new
                        {
                            Id = 4,
                            Eliminado = false,
                            Nombre = "Tecnicatura Superior en Enfermeria"
                        },
                        new
                        {
                            Id = 5,
                            Eliminado = false,
                            Nombre = "Profesorado de Educación Secundaria en Ciencias de la Administración"
                        },
                        new
                        {
                            Id = 6,
                            Eliminado = false,
                            Nombre = "Profesorado de Educación Inicial"
                        },
                        new
                        {
                            Id = 7,
                            Eliminado = false,
                            Nombre = "Profesorado de Educación Secundaria en Economía"
                        },
                        new
                        {
                            Id = 8,
                            Eliminado = false,
                            Nombre = "Profesorado de Educación Tecnológica"
                        },
                        new
                        {
                            Id = 9,
                            Eliminado = false,
                            Nombre = "Licenciatura en Cooperativismo y Mutualismo"
                        });
                });

            modelBuilder.Entity("InscripcionWeb.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AñoCursadoId")
                        .HasColumnType("int");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AñoCursadoId");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("InscripcionWeb.Models.AñoCursado", b =>
                {
                    b.HasOne("InscripcionWeb.Models.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InscripcionWeb.Models.Materia", b =>
                {
                    b.HasOne("InscripcionWeb.Models.AñoCursado", "AñoCursado")
                        .WithMany()
                        .HasForeignKey("AñoCursadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
