// <auto-generated />
using InscripcionWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InscripcionWeb.Migrations
{
    [DbContext(typeof(InscripcionWebContext))]
    [Migration("20210630172731_agregamosIdsAModelosDetalles")]
    partial class agregamosIdsAModelosDetalles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InscripcionWeb.Models.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Telefono")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Alumnos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Valle",
                            Dni = 37454714,
                            Eliminado = false,
                            Email = "ivanvallesj@gmail.com",
                            Nombre = "Carlos Ivan ",
                            Telefono = 3498459297.0
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Colombo",
                            Dni = 38584798,
                            Eliminado = false,
                            Email = "juancolombosj@gmail.com",
                            Nombre = "Juan Pablo ",
                            Telefono = 3498459299.0
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Córdoba",
                            Dni = 38957452,
                            Eliminado = false,
                            Email = "rami@gmail.com",
                            Nombre = "Ramiro ",
                            Telefono = 3498459298.0
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "Sabino",
                            Dni = 39625852,
                            Eliminado = false,
                            Email = "mati@gmail.com",
                            Nombre = "Matias ",
                            Telefono = 3498459295.0
                        },
                        new
                        {
                            Id = 5,
                            Apellido = "Mangini",
                            Dni = 37154825,
                            Eliminado = false,
                            Email = "jere@gmail.com",
                            Nombre = "Jeremias  ",
                            Telefono = 3498459294.0
                        },
                        new
                        {
                            Id = 6,
                            Apellido = " Paulon ",
                            Dni = 37124896,
                            Eliminado = false,
                            Email = "corado@gmail.com",
                            Nombre = "Conrado",
                            Telefono = 3498459293.0
                        },
                        new
                        {
                            Id = 7,
                            Apellido = " Gomez ",
                            Dni = 38957412,
                            Eliminado = false,
                            Email = "nahuel@gmail.com",
                            Nombre = "Nahuel",
                            Telefono = 3498459292.0
                        },
                        new
                        {
                            Id = 8,
                            Apellido = " Barreto",
                            Dni = 39658745,
                            Eliminado = false,
                            Email = "santi@gmail.com",
                            Nombre = "Santiago",
                            Telefono = 3498459291.0
                        });
                });

            modelBuilder.Entity("InscripcionWeb.Models.AñoCursado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.ToTable("AñoCursados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarreraId = 1,
                            Eliminado = false,
                            Nombre = "Primero"
                        },
                        new
                        {
                            Id = 2,
                            CarreraId = 1,
                            Eliminado = false,
                            Nombre = "Segundo"
                        },
                        new
                        {
                            Id = 3,
                            CarreraId = 1,
                            Eliminado = false,
                            Nombre = "Tercero"
                        },
                        new
                        {
                            Id = 4,
                            CarreraId = 2,
                            Eliminado = false,
                            Nombre = "Primero"
                        },
                        new
                        {
                            Id = 5,
                            CarreraId = 2,
                            Eliminado = false,
                            Nombre = "Segundo"
                        },
                        new
                        {
                            Id = 6,
                            CarreraId = 2,
                            Eliminado = false,
                            Nombre = "Tercero"
                        },
                        new
                        {
                            Id = 7,
                            CarreraId = 3,
                            Eliminado = false,
                            Nombre = "Primero"
                        },
                        new
                        {
                            Id = 8,
                            CarreraId = 3,
                            Eliminado = false,
                            Nombre = "Segundo"
                        },
                        new
                        {
                            Id = 9,
                            CarreraId = 3,
                            Eliminado = false,
                            Nombre = "Tercero"
                        },
                        new
                        {
                            Id = 10,
                            CarreraId = 4,
                            Eliminado = false,
                            Nombre = "Primero"
                        },
                        new
                        {
                            Id = 11,
                            CarreraId = 4,
                            Eliminado = false,
                            Nombre = "Segundo"
                        },
                        new
                        {
                            Id = 12,
                            CarreraId = 4,
                            Eliminado = false,
                            Nombre = "Tercero"
                        },
                        new
                        {
                            Id = 13,
                            CarreraId = 5,
                            Eliminado = false,
                            Nombre = "Primero"
                        },
                        new
                        {
                            Id = 14,
                            CarreraId = 5,
                            Eliminado = false,
                            Nombre = "Segundo"
                        },
                        new
                        {
                            Id = 15,
                            CarreraId = 5,
                            Eliminado = false,
                            Nombre = "Tercero"
                        },
                        new
                        {
                            Id = 16,
                            CarreraId = 5,
                            Eliminado = false,
                            Nombre = "Cuarto"
                        },
                        new
                        {
                            Id = 17,
                            CarreraId = 6,
                            Eliminado = false,
                            Nombre = "Primero"
                        },
                        new
                        {
                            Id = 18,
                            CarreraId = 6,
                            Eliminado = false,
                            Nombre = "Segundo"
                        },
                        new
                        {
                            Id = 19,
                            CarreraId = 6,
                            Eliminado = false,
                            Nombre = "Tercero"
                        },
                        new
                        {
                            Id = 20,
                            CarreraId = 6,
                            Eliminado = false,
                            Nombre = "Cuarto"
                        },
                        new
                        {
                            Id = 21,
                            CarreraId = 7,
                            Eliminado = false,
                            Nombre = "Primero"
                        },
                        new
                        {
                            Id = 22,
                            CarreraId = 7,
                            Eliminado = false,
                            Nombre = "Segundo"
                        },
                        new
                        {
                            Id = 23,
                            CarreraId = 7,
                            Eliminado = false,
                            Nombre = "Tercero"
                        },
                        new
                        {
                            Id = 24,
                            CarreraId = 7,
                            Eliminado = false,
                            Nombre = "Cuarto"
                        },
                        new
                        {
                            Id = 25,
                            CarreraId = 8,
                            Eliminado = false,
                            Nombre = "Primero"
                        },
                        new
                        {
                            Id = 26,
                            CarreraId = 8,
                            Eliminado = false,
                            Nombre = "Segundo"
                        },
                        new
                        {
                            Id = 27,
                            CarreraId = 8,
                            Eliminado = false,
                            Nombre = "Tercero"
                        },
                        new
                        {
                            Id = 28,
                            CarreraId = 8,
                            Eliminado = false,
                            Nombre = "Cuarto"
                        },
                        new
                        {
                            Id = 29,
                            CarreraId = 9,
                            Eliminado = false,
                            Nombre = "Primero"
                        });
                });

            modelBuilder.Entity("InscripcionWeb.Models.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carreras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Eliminado = false,
                            Nombre = "Tecnicatura Superior en Desarrollo de Software"
                        },
                        new
                        {
                            Id = 2,
                            Eliminado = false,
                            Nombre = "Tecnicatura Superior en Soporte de Infraestructura"
                        },
                        new
                        {
                            Id = 3,
                            Eliminado = false,
                            Nombre = "Tecnicatura Superior en Gestion de las Organizaciones"
                        },
                        new
                        {
                            Id = 4,
                            Eliminado = false,
                            Nombre = "Tecnicatura Superior en Enfermeria"
                        },
                        new
                        {
                            Id = 5,
                            Eliminado = false,
                            Nombre = "Profesorado de Educación Secundaria en Ciencias de la Administración"
                        },
                        new
                        {
                            Id = 6,
                            Eliminado = false,
                            Nombre = "Profesorado de Educación Inicial"
                        },
                        new
                        {
                            Id = 7,
                            Eliminado = false,
                            Nombre = "Profesorado de Educación Secundaria en Economía"
                        },
                        new
                        {
                            Id = 8,
                            Eliminado = false,
                            Nombre = "Profesorado de Educación Tecnológica"
                        },
                        new
                        {
                            Id = 9,
                            Eliminado = false,
                            Nombre = "Licenciatura en Cooperativismo y Mutualismo"
                        });
                });

            modelBuilder.Entity("InscripcionWeb.Models.DetalleAlumnoCarrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("CarreraId");

                    b.ToTable("DetallesAlumnosCarreras");
                });

            modelBuilder.Entity("InscripcionWeb.Models.DetalleAlumnoMateria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("MateriaId");

                    b.ToTable("DetallesAlumnosMaterias");
                });

            modelBuilder.Entity("InscripcionWeb.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AñoCursadoId")
                        .HasColumnType("int");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AñoCursadoId");

                    b.ToTable("Materias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AñoCursadoId = 25,
                            Eliminado = false,
                            Nombre = "Pedagogía"
                        },
                        new
                        {
                            Id = 2,
                            AñoCursadoId = 25,
                            Eliminado = false,
                            Nombre = "Movimiento y Cuerpo"
                        },
                        new
                        {
                            Id = 3,
                            AñoCursadoId = 25,
                            Eliminado = false,
                            Nombre = "Práctica Docente I: Escenarios Educativos"
                        },
                        new
                        {
                            Id = 4,
                            AñoCursadoId = 25,
                            Eliminado = false,
                            Nombre = "Introducción a la Tecnología"
                        },
                        new
                        {
                            Id = 5,
                            AñoCursadoId = 25,
                            Eliminado = false,
                            Nombre = "Historia de la Tecnología"
                        },
                        new
                        {
                            Id = 6,
                            AñoCursadoId = 25,
                            Eliminado = false,
                            Nombre = "Diseño y Producción de la Técnología 1"
                        },
                        new
                        {
                            Id = 7,
                            AñoCursadoId = 25,
                            Eliminado = false,
                            Nombre = "Matemática"
                        },
                        new
                        {
                            Id = 8,
                            AñoCursadoId = 25,
                            Eliminado = false,
                            Nombre = "Física"
                        },
                        new
                        {
                            Id = 9,
                            AñoCursadoId = 26,
                            Eliminado = false,
                            Nombre = "Psicología de la Educación"
                        },
                        new
                        {
                            Id = 10,
                            AñoCursadoId = 26,
                            Eliminado = false,
                            Nombre = "Didáctica y Curriculum"
                        },
                        new
                        {
                            Id = 11,
                            AñoCursadoId = 26,
                            Eliminado = false,
                            Nombre = "Instituciones Educativas"
                        },
                        new
                        {
                            Id = 12,
                            AñoCursadoId = 26,
                            Eliminado = false,
                            Nombre = "Práctica Docente II: La Institución Escolar"
                        },
                        new
                        {
                            Id = 13,
                            AñoCursadoId = 26,
                            Eliminado = false,
                            Nombre = "Sujetos de la Educación I"
                        },
                        new
                        {
                            Id = 14,
                            AñoCursadoId = 26,
                            Eliminado = false,
                            Nombre = "Tic para la Enseñanza"
                        },
                        new
                        {
                            Id = 15,
                            AñoCursadoId = 26,
                            Eliminado = false,
                            Nombre = "Procesos Productivos"
                        },
                        new
                        {
                            Id = 16,
                            AñoCursadoId = 26,
                            Eliminado = false,
                            Nombre = "Tecnológica II"
                        },
                        new
                        {
                            Id = 17,
                            AñoCursadoId = 26,
                            Eliminado = false,
                            Nombre = "Didáctica Específica I"
                        },
                        new
                        {
                            Id = 18,
                            AñoCursadoId = 27,
                            Eliminado = false,
                            Nombre = "Filosofía y Educación"
                        },
                        new
                        {
                            Id = 19,
                            AñoCursadoId = 27,
                            Eliminado = false,
                            Nombre = "Historia Social de la Educación"
                        },
                        new
                        {
                            Id = 20,
                            AñoCursadoId = 27,
                            Eliminado = false,
                            Nombre = "Metodología de la Investigación"
                        },
                        new
                        {
                            Id = 21,
                            AñoCursadoId = 27,
                            Eliminado = false,
                            Nombre = "Práctica Docente III: La Clase"
                        },
                        new
                        {
                            Id = 22,
                            AñoCursadoId = 27,
                            Eliminado = false,
                            Nombre = "Sujetos de la Educación II"
                        },
                        new
                        {
                            Id = 23,
                            AñoCursadoId = 27,
                            Eliminado = false,
                            Nombre = "Materiales"
                        },
                        new
                        {
                            Id = 24,
                            AñoCursadoId = 27,
                            Eliminado = false,
                            Nombre = "Química "
                        },
                        new
                        {
                            Id = 25,
                            AñoCursadoId = 27,
                            Eliminado = false,
                            Nombre = "Procesos de Control"
                        },
                        new
                        {
                            Id = 26,
                            AñoCursadoId = 27,
                            Eliminado = false,
                            Nombre = "Tecnologías Regionales "
                        },
                        new
                        {
                            Id = 27,
                            AñoCursadoId = 27,
                            Eliminado = false,
                            Nombre = "Diseño y Producción"
                        },
                        new
                        {
                            Id = 28,
                            AñoCursadoId = 27,
                            Eliminado = false,
                            Nombre = "Tecnológica III"
                        },
                        new
                        {
                            Id = 29,
                            AñoCursadoId = 27,
                            Eliminado = false,
                            Nombre = "Didáctica Específica II"
                        },
                        new
                        {
                            Id = 30,
                            AñoCursadoId = 28,
                            Eliminado = false,
                            Nombre = "Ética y Trabajo Docente"
                        },
                        new
                        {
                            Id = 31,
                            AñoCursadoId = 28,
                            Eliminado = false,
                            Nombre = "Educación Sexual Integral"
                        },
                        new
                        {
                            Id = 32,
                            AñoCursadoId = 28,
                            Eliminado = false,
                            Nombre = "Unidades de Definición Institucional I"
                        },
                        new
                        {
                            Id = 33,
                            AñoCursadoId = 28,
                            Eliminado = false,
                            Nombre = "Unidades de Definición Institucional II"
                        },
                        new
                        {
                            Id = 34,
                            AñoCursadoId = 28,
                            Eliminado = false,
                            Nombre = "Prácticas de Investigación"
                        },
                        new
                        {
                            Id = 35,
                            AñoCursadoId = 28,
                            Eliminado = false,
                            Nombre = "Práctica Docente IV: El Rol Docente y su Práctica"
                        },
                        new
                        {
                            Id = 36,
                            AñoCursadoId = 28,
                            Eliminado = false,
                            Nombre = "Biotecnología "
                        },
                        new
                        {
                            Id = 37,
                            AñoCursadoId = 28,
                            Eliminado = false,
                            Nombre = "Procesos de Comunicación "
                        },
                        new
                        {
                            Id = 38,
                            AñoCursadoId = 28,
                            Eliminado = false,
                            Nombre = "Problemáticas Sociotécnicas "
                        },
                        new
                        {
                            Id = 39,
                            AñoCursadoId = 28,
                            Eliminado = false,
                            Nombre = "Diseño y Producción Tecnológica IV"
                        },
                        new
                        {
                            Id = 40,
                            AñoCursadoId = 28,
                            Eliminado = false,
                            Nombre = "Taller de Producción Didáctica"
                        },
                        new
                        {
                            Id = 41,
                            AñoCursadoId = 10,
                            Eliminado = false,
                            Nombre = "Comunicación"
                        },
                        new
                        {
                            Id = 42,
                            AñoCursadoId = 10,
                            Eliminado = false,
                            Nombre = "Unidad de Definición Institucional I"
                        },
                        new
                        {
                            Id = 43,
                            AñoCursadoId = 10,
                            Eliminado = false,
                            Nombre = "Salud Pública"
                        },
                        new
                        {
                            Id = 44,
                            AñoCursadoId = 10,
                            Eliminado = false,
                            Nombre = "Biología Humana I"
                        },
                        new
                        {
                            Id = 45,
                            AñoCursadoId = 10,
                            Eliminado = false,
                            Nombre = "Sujeto, Cultura y Sociedad I"
                        },
                        new
                        {
                            Id = 46,
                            AñoCursadoId = 10,
                            Eliminado = false,
                            Nombre = "Fundaméntos del Cuidado en Enfermería"
                        },
                        new
                        {
                            Id = 47,
                            AñoCursadoId = 10,
                            Eliminado = false,
                            Nombre = "Cuidados de Enfermería en la Comunidad y en la Familia"
                        },
                        new
                        {
                            Id = 48,
                            AñoCursadoId = 10,
                            Eliminado = false,
                            Nombre = "Práctica Profesionalizante I"
                        },
                        new
                        {
                            Id = 49,
                            AñoCursadoId = 11,
                            Eliminado = false,
                            Nombre = "Problemáticas Socio Contemporáneas"
                        },
                        new
                        {
                            Id = 50,
                            AñoCursadoId = 11,
                            Eliminado = false,
                            Nombre = "Unidad de Definición Institucional II"
                        },
                        new
                        {
                            Id = 51,
                            AñoCursadoId = 11,
                            Eliminado = false,
                            Nombre = "Informática en Salud"
                        },
                        new
                        {
                            Id = 52,
                            AñoCursadoId = 11,
                            Eliminado = false,
                            Nombre = "Sujeto, Cultura y Sociedad II"
                        },
                        new
                        {
                            Id = 53,
                            AñoCursadoId = 11,
                            Eliminado = false,
                            Nombre = "Biología Humana II"
                        },
                        new
                        {
                            Id = 54,
                            AñoCursadoId = 11,
                            Eliminado = false,
                            Nombre = "Bioseguridad y Medio Ambiente en el Trabajo"
                        },
                        new
                        {
                            Id = 55,
                            AñoCursadoId = 11,
                            Eliminado = false,
                            Nombre = "Farmacología en Enfermería"
                        },
                        new
                        {
                            Id = 56,
                            AñoCursadoId = 11,
                            Eliminado = false,
                            Nombre = "Cuidados de Enfermería a los Adultos y Adultos Mayores"
                        },
                        new
                        {
                            Id = 57,
                            AñoCursadoId = 11,
                            Eliminado = false,
                            Nombre = "Práctica Profesionalizante II"
                        },
                        new
                        {
                            Id = 58,
                            AñoCursadoId = 12,
                            Eliminado = false,
                            Nombre = "Ética y Responsabilidad Social"
                        },
                        new
                        {
                            Id = 59,
                            AñoCursadoId = 12,
                            Eliminado = false,
                            Nombre = "Derecho y Legislación Laboral"
                        },
                        new
                        {
                            Id = 60,
                            AñoCursadoId = 12,
                            Eliminado = false,
                            Nombre = "Inglés Técnico"
                        },
                        new
                        {
                            Id = 61,
                            AñoCursadoId = 12,
                            Eliminado = false,
                            Nombre = "Organización y Gestión en Instituciones de Salud"
                        },
                        new
                        {
                            Id = 62,
                            AñoCursadoId = 12,
                            Eliminado = false,
                            Nombre = "Investigación en Enfermería"
                        },
                        new
                        {
                            Id = 63,
                            AñoCursadoId = 12,
                            Eliminado = false,
                            Nombre = "Cuidados de Enfermería en Salud Mental"
                        },
                        new
                        {
                            Id = 64,
                            AñoCursadoId = 12,
                            Eliminado = false,
                            Nombre = "Cuidados de Enfermería al Niño y al Adolescente"
                        },
                        new
                        {
                            Id = 65,
                            AñoCursadoId = 12,
                            Eliminado = false,
                            Nombre = "Práctica Profesionalizante III"
                        },
                        new
                        {
                            Id = 66,
                            AñoCursadoId = 4,
                            Eliminado = false,
                            Nombre = "Comunicación (1° cuat.)"
                        },
                        new
                        {
                            Id = 67,
                            AñoCursadoId = 4,
                            Eliminado = false,
                            Nombre = "Unidad de definición Institucional (2° cuat.)"
                        },
                        new
                        {
                            Id = 68,
                            AñoCursadoId = 4,
                            Eliminado = false,
                            Nombre = "Matemática"
                        },
                        new
                        {
                            Id = 69,
                            AñoCursadoId = 4,
                            Eliminado = false,
                            Nombre = "Física Aplicada a las Tecnologías de la Información"
                        },
                        new
                        {
                            Id = 70,
                            AñoCursadoId = 4,
                            Eliminado = false,
                            Nombre = "Administración"
                        },
                        new
                        {
                            Id = 71,
                            AñoCursadoId = 4,
                            Eliminado = false,
                            Nombre = "Inglés Técnico"
                        },
                        new
                        {
                            Id = 72,
                            AñoCursadoId = 4,
                            Eliminado = false,
                            Nombre = "Arquitectura de las Computadoras"
                        },
                        new
                        {
                            Id = 73,
                            AñoCursadoId = 4,
                            Eliminado = false,
                            Nombre = "Lógica y Programación"
                        },
                        new
                        {
                            Id = 74,
                            AñoCursadoId = 4,
                            Eliminado = false,
                            Nombre = "Infraestructura de Redes I"
                        },
                        new
                        {
                            Id = 75,
                            AñoCursadoId = 5,
                            Eliminado = false,
                            Nombre = "Problemáticas Socio Contemporáneas (1° cuat.)"
                        },
                        new
                        {
                            Id = 76,
                            AñoCursadoId = 5,
                            Eliminado = false,
                            Nombre = "Unidad de definición Institucional (2° cuat.)"
                        },
                        new
                        {
                            Id = 77,
                            AñoCursadoId = 5,
                            Eliminado = false,
                            Nombre = "Innovación y Desarrollo Emprendedor"
                        },
                        new
                        {
                            Id = 78,
                            AñoCursadoId = 5,
                            Eliminado = false,
                            Nombre = "Estadística"
                        },
                        new
                        {
                            Id = 79,
                            AñoCursadoId = 5,
                            Eliminado = false,
                            Nombre = "Sistemas Operativos"
                        },
                        new
                        {
                            Id = 80,
                            AñoCursadoId = 5,
                            Eliminado = false,
                            Nombre = "Algoritmos y Estructuras de Datos"
                        },
                        new
                        {
                            Id = 81,
                            AñoCursadoId = 5,
                            Eliminado = false,
                            Nombre = "Base de Datos"
                        },
                        new
                        {
                            Id = 82,
                            AñoCursadoId = 5,
                            Eliminado = false,
                            Nombre = "Infraestructura de Datos II"
                        },
                        new
                        {
                            Id = 83,
                            AñoCursadoId = 5,
                            Eliminado = false,
                            Nombre = "Práctica Profesionalizante I"
                        },
                        new
                        {
                            Id = 84,
                            AñoCursadoId = 6,
                            Eliminado = false,
                            Nombre = "Ética y Responsabilidad Social"
                        },
                        new
                        {
                            Id = 85,
                            AñoCursadoId = 6,
                            Eliminado = false,
                            Nombre = "Derecho y Legislación Laboral"
                        },
                        new
                        {
                            Id = 86,
                            AñoCursadoId = 6,
                            Eliminado = false,
                            Nombre = "Administración de Base de Datos"
                        },
                        new
                        {
                            Id = 87,
                            AñoCursadoId = 6,
                            Eliminado = false,
                            Nombre = "Integridad y Migración de Datos"
                        },
                        new
                        {
                            Id = 88,
                            AñoCursadoId = 6,
                            Eliminado = false,
                            Nombre = "Seguridad de los Sistemas"
                        },
                        new
                        {
                            Id = 89,
                            AñoCursadoId = 6,
                            Eliminado = false,
                            Nombre = "Administración de Sistemas"
                        },
                        new
                        {
                            Id = 90,
                            AñoCursadoId = 6,
                            Eliminado = false,
                            Nombre = "Operativos y Redes"
                        },
                        new
                        {
                            Id = 91,
                            AñoCursadoId = 6,
                            Eliminado = false,
                            Nombre = "Práctica Profesionalizante II"
                        },
                        new
                        {
                            Id = 92,
                            AñoCursadoId = 1,
                            Eliminado = false,
                            Nombre = "Comunicación (1° cuat.)"
                        },
                        new
                        {
                            Id = 93,
                            AñoCursadoId = 1,
                            Eliminado = false,
                            Nombre = "Unidad de definición Institucional (2° cuat.)"
                        },
                        new
                        {
                            Id = 94,
                            AñoCursadoId = 1,
                            Eliminado = false,
                            Nombre = "Matemática"
                        },
                        new
                        {
                            Id = 95,
                            AñoCursadoId = 1,
                            Eliminado = false,
                            Nombre = "Inglés Técnico I"
                        },
                        new
                        {
                            Id = 96,
                            AñoCursadoId = 1,
                            Eliminado = false,
                            Nombre = "Administración"
                        },
                        new
                        {
                            Id = 97,
                            AñoCursadoId = 1,
                            Eliminado = false,
                            Nombre = "Tecnología de la Información"
                        },
                        new
                        {
                            Id = 98,
                            AñoCursadoId = 1,
                            Eliminado = false,
                            Nombre = "Lógica y Estructura de Datos"
                        },
                        new
                        {
                            Id = 99,
                            AñoCursadoId = 1,
                            Eliminado = false,
                            Nombre = "Ingeniería de Software I"
                        },
                        new
                        {
                            Id = 100,
                            AñoCursadoId = 1,
                            Eliminado = false,
                            Nombre = "Sistemas Operativos"
                        },
                        new
                        {
                            Id = 101,
                            AñoCursadoId = 2,
                            Eliminado = false,
                            Nombre = "Problemáticas Socio Contemporáneas (1° cuat.)"
                        },
                        new
                        {
                            Id = 102,
                            AñoCursadoId = 2,
                            Eliminado = false,
                            Nombre = "Unidad de definición Institucional (2° cuat.)"
                        },
                        new
                        {
                            Id = 103,
                            AñoCursadoId = 2,
                            Eliminado = false,
                            Nombre = "Inglés Técnico II"
                        },
                        new
                        {
                            Id = 104,
                            AñoCursadoId = 2,
                            Eliminado = false,
                            Nombre = "Innovación y Desarrollo Emprendedor"
                        },
                        new
                        {
                            Id = 105,
                            AñoCursadoId = 2,
                            Eliminado = false,
                            Nombre = "Estadística"
                        },
                        new
                        {
                            Id = 106,
                            AñoCursadoId = 2,
                            Eliminado = false,
                            Nombre = "Programación I"
                        },
                        new
                        {
                            Id = 107,
                            AñoCursadoId = 2,
                            Eliminado = false,
                            Nombre = "Ingeniería de Software II"
                        },
                        new
                        {
                            Id = 108,
                            AñoCursadoId = 2,
                            Eliminado = false,
                            Nombre = "Base de Datos I"
                        },
                        new
                        {
                            Id = 109,
                            AñoCursadoId = 2,
                            Eliminado = false,
                            Nombre = "Práctica Profesionalizante I"
                        },
                        new
                        {
                            Id = 110,
                            AñoCursadoId = 3,
                            Eliminado = false,
                            Nombre = "Ética y Responsabilidad Social"
                        },
                        new
                        {
                            Id = 111,
                            AñoCursadoId = 3,
                            Eliminado = false,
                            Nombre = "Derecho y Legislación Laboral "
                        },
                        new
                        {
                            Id = 112,
                            AñoCursadoId = 3,
                            Eliminado = false,
                            Nombre = "Redes y Comunicación"
                        },
                        new
                        {
                            Id = 113,
                            AñoCursadoId = 3,
                            Eliminado = false,
                            Nombre = "Programación II"
                        },
                        new
                        {
                            Id = 114,
                            AñoCursadoId = 3,
                            Eliminado = false,
                            Nombre = "Gestión de Proyectos de Software"
                        },
                        new
                        {
                            Id = 115,
                            AñoCursadoId = 3,
                            Eliminado = false,
                            Nombre = "Base de Datos II"
                        },
                        new
                        {
                            Id = 116,
                            AñoCursadoId = 3,
                            Eliminado = false,
                            Nombre = "Práctica Profesionalizante II"
                        },
                        new
                        {
                            Id = 117,
                            AñoCursadoId = 7,
                            Eliminado = false,
                            Nombre = "Comunicación (1° cuat.)"
                        },
                        new
                        {
                            Id = 118,
                            AñoCursadoId = 7,
                            Eliminado = false,
                            Nombre = "Unidad de Definición Institucional (2° cuat.)"
                        },
                        new
                        {
                            Id = 119,
                            AñoCursadoId = 7,
                            Eliminado = false,
                            Nombre = "Economía "
                        },
                        new
                        {
                            Id = 120,
                            AñoCursadoId = 7,
                            Eliminado = false,
                            Nombre = "Matemática y Estadística"
                        },
                        new
                        {
                            Id = 121,
                            AñoCursadoId = 7,
                            Eliminado = false,
                            Nombre = "Contabilidad"
                        },
                        new
                        {
                            Id = 122,
                            AñoCursadoId = 7,
                            Eliminado = false,
                            Nombre = "Informática "
                        },
                        new
                        {
                            Id = 123,
                            AñoCursadoId = 7,
                            Eliminado = false,
                            Nombre = "Administración "
                        },
                        new
                        {
                            Id = 124,
                            AñoCursadoId = 7,
                            Eliminado = false,
                            Nombre = "Gestión de la Producción "
                        },
                        new
                        {
                            Id = 125,
                            AñoCursadoId = 7,
                            Eliminado = false,
                            Nombre = "Gestión del Talento "
                        },
                        new
                        {
                            Id = 126,
                            AñoCursadoId = 7,
                            Eliminado = false,
                            Nombre = "Humano"
                        },
                        new
                        {
                            Id = 127,
                            AñoCursadoId = 8,
                            Eliminado = false,
                            Nombre = "Problemáticas Contemporáneas"
                        },
                        new
                        {
                            Id = 128,
                            AñoCursadoId = 8,
                            Eliminado = false,
                            Nombre = "Unidad de Definición Institucional II (2° cuat.)"
                        },
                        new
                        {
                            Id = 129,
                            AñoCursadoId = 8,
                            Eliminado = false,
                            Nombre = "Innovación y Desarrollo Emprendedor"
                        },
                        new
                        {
                            Id = 130,
                            AñoCursadoId = 8,
                            Eliminado = false,
                            Nombre = "Inglés Técnico"
                        },
                        new
                        {
                            Id = 131,
                            AñoCursadoId = 8,
                            Eliminado = false,
                            Nombre = "Legislación Comercial y Tributaria "
                        },
                        new
                        {
                            Id = 132,
                            AñoCursadoId = 8,
                            Eliminado = false,
                            Nombre = "Gestión de Comercialización e Investigación Comercia"
                        },
                        new
                        {
                            Id = 133,
                            AñoCursadoId = 8,
                            Eliminado = false,
                            Nombre = "Gestión de Costos"
                        },
                        new
                        {
                            Id = 134,
                            AñoCursadoId = 8,
                            Eliminado = false,
                            Nombre = "Gestión Contable"
                        },
                        new
                        {
                            Id = 135,
                            AñoCursadoId = 8,
                            Eliminado = false,
                            Nombre = "Práctica Profesionalizante I"
                        },
                        new
                        {
                            Id = 136,
                            AñoCursadoId = 9,
                            Eliminado = false,
                            Nombre = "Gestión de Seguridad, Salud Ocupacional y Medio Ambiente"
                        },
                        new
                        {
                            Id = 137,
                            AñoCursadoId = 9,
                            Eliminado = false,
                            Nombre = "Ética y Responsabilidad Social"
                        },
                        new
                        {
                            Id = 138,
                            AñoCursadoId = 9,
                            Eliminado = false,
                            Nombre = "Legislación Laboral"
                        },
                        new
                        {
                            Id = 139,
                            AñoCursadoId = 9,
                            Eliminado = false,
                            Nombre = "Estrategia Empresarial"
                        },
                        new
                        {
                            Id = 140,
                            AñoCursadoId = 9,
                            Eliminado = false,
                            Nombre = "Sistema de Información para la Gestión de las Organizaciones "
                        },
                        new
                        {
                            Id = 141,
                            AñoCursadoId = 9,
                            Eliminado = false,
                            Nombre = "Gestión Financiera"
                        },
                        new
                        {
                            Id = 142,
                            AñoCursadoId = 9,
                            Eliminado = false,
                            Nombre = "Evaluación y Administración de Proyectos de Inversión"
                        },
                        new
                        {
                            Id = 143,
                            AñoCursadoId = 9,
                            Eliminado = false,
                            Nombre = "Control de Gestión"
                        },
                        new
                        {
                            Id = 144,
                            AñoCursadoId = 9,
                            Eliminado = false,
                            Nombre = "Practicas Profesionalizante II"
                        },
                        new
                        {
                            Id = 145,
                            AñoCursadoId = 13,
                            Eliminado = false,
                            Nombre = "Pedagogía"
                        },
                        new
                        {
                            Id = 146,
                            AñoCursadoId = 13,
                            Eliminado = false,
                            Nombre = "UCCV Sociología"
                        },
                        new
                        {
                            Id = 147,
                            AñoCursadoId = 13,
                            Eliminado = false,
                            Nombre = "Administración General"
                        },
                        new
                        {
                            Id = 148,
                            AñoCursadoId = 13,
                            Eliminado = false,
                            Nombre = "Administración I"
                        },
                        new
                        {
                            Id = 149,
                            AñoCursadoId = 13,
                            Eliminado = false,
                            Nombre = "Sistema de Información Contable I"
                        },
                        new
                        {
                            Id = 150,
                            AñoCursadoId = 13,
                            Eliminado = false,
                            Nombre = "Construcción de Ciudadanía"
                        },
                        new
                        {
                            Id = 151,
                            AñoCursadoId = 13,
                            Eliminado = false,
                            Nombre = "Historia Económica"
                        },
                        new
                        {
                            Id = 152,
                            AñoCursadoId = 13,
                            Eliminado = false,
                            Nombre = "Matemática"
                        },
                        new
                        {
                            Id = 153,
                            AñoCursadoId = 13,
                            Eliminado = false,
                            Nombre = "Práctica Docente I"
                        },
                        new
                        {
                            Id = 154,
                            AñoCursadoId = 14,
                            Eliminado = false,
                            Nombre = "Instituciones Educativas"
                        },
                        new
                        {
                            Id = 155,
                            AñoCursadoId = 14,
                            Eliminado = false,
                            Nombre = "Didáctica y Curriculum"
                        },
                        new
                        {
                            Id = 156,
                            AñoCursadoId = 14,
                            Eliminado = false,
                            Nombre = "Psicología y Educación"
                        },
                        new
                        {
                            Id = 157,
                            AñoCursadoId = 14,
                            Eliminado = false,
                            Nombre = "Administración II"
                        },
                        new
                        {
                            Id = 158,
                            AñoCursadoId = 14,
                            Eliminado = false,
                            Nombre = "Sistema de Información Contable II"
                        },
                        new
                        {
                            Id = 159,
                            AñoCursadoId = 14,
                            Eliminado = false,
                            Nombre = "Derecho I"
                        },
                        new
                        {
                            Id = 160,
                            AñoCursadoId = 14,
                            Eliminado = false,
                            Nombre = "Economía"
                        },
                        new
                        {
                            Id = 161,
                            AñoCursadoId = 14,
                            Eliminado = false,
                            Nombre = "Estadística Aplicada"
                        },
                        new
                        {
                            Id = 162,
                            AñoCursadoId = 14,
                            Eliminado = false,
                            Nombre = "Didáctica de la Administración I"
                        },
                        new
                        {
                            Id = 163,
                            AñoCursadoId = 14,
                            Eliminado = false,
                            Nombre = "Práctica Docencia II"
                        },
                        new
                        {
                            Id = 164,
                            AñoCursadoId = 15,
                            Eliminado = false,
                            Nombre = "Historia y Política de la Educación Argentina "
                        },
                        new
                        {
                            Id = 165,
                            AñoCursadoId = 15,
                            Eliminado = false,
                            Nombre = "Filosofía"
                        },
                        new
                        {
                            Id = 166,
                            AñoCursadoId = 15,
                            Eliminado = false,
                            Nombre = "Metodología de la Investigación"
                        },
                        new
                        {
                            Id = 167,
                            AñoCursadoId = 15,
                            Eliminado = false,
                            Nombre = "Administración III"
                        },
                        new
                        {
                            Id = 168,
                            AñoCursadoId = 15,
                            Eliminado = false,
                            Nombre = "Sistema de Información Contable III"
                        },
                        new
                        {
                            Id = 169,
                            AñoCursadoId = 15,
                            Eliminado = false,
                            Nombre = "Práctica Impositiva y Laboral"
                        },
                        new
                        {
                            Id = 170,
                            AñoCursadoId = 15,
                            Eliminado = false,
                            Nombre = "Derecho II"
                        },
                        new
                        {
                            Id = 171,
                            AñoCursadoId = 15,
                            Eliminado = false,
                            Nombre = "Didáctica de la Administración II"
                        },
                        new
                        {
                            Id = 172,
                            AñoCursadoId = 15,
                            Eliminado = false,
                            Nombre = "Sujetos de la Educación Secundaria"
                        },
                        new
                        {
                            Id = 173,
                            AñoCursadoId = 15,
                            Eliminado = false,
                            Nombre = "Práctica Docente III"
                        },
                        new
                        {
                            Id = 174,
                            AñoCursadoId = 15,
                            Eliminado = false,
                            Nombre = "Producción de los Recursos Didácticos I"
                        },
                        new
                        {
                            Id = 175,
                            AñoCursadoId = 16,
                            Eliminado = false,
                            Nombre = "Ética y Trabajo Docente"
                        },
                        new
                        {
                            Id = 176,
                            AñoCursadoId = 16,
                            Eliminado = false,
                            Nombre = "Educación Sexual Integral"
                        },
                        new
                        {
                            Id = 177,
                            AñoCursadoId = 16,
                            Eliminado = false,
                            Nombre = "UCCV Comunicación Social"
                        },
                        new
                        {
                            Id = 178,
                            AñoCursadoId = 16,
                            Eliminado = false,
                            Nombre = "Administración IV"
                        },
                        new
                        {
                            Id = 179,
                            AñoCursadoId = 16,
                            Eliminado = false,
                            Nombre = "Gestión Organizacional"
                        },
                        new
                        {
                            Id = 180,
                            AñoCursadoId = 16,
                            Eliminado = false,
                            Nombre = "Matemática Financiera"
                        },
                        new
                        {
                            Id = 181,
                            AñoCursadoId = 16,
                            Eliminado = false,
                            Nombre = "Prácticas de Investigación"
                        },
                        new
                        {
                            Id = 182,
                            AñoCursadoId = 16,
                            Eliminado = false,
                            Nombre = "Práctica Docente IV (Residencia)"
                        },
                        new
                        {
                            Id = 183,
                            AñoCursadoId = 16,
                            Eliminado = false,
                            Nombre = "Producción de los Recursos Didácticos II"
                        },
                        new
                        {
                            Id = 184,
                            AñoCursadoId = 16,
                            Eliminado = false,
                            Nombre = "Unidad de Definición Institucional"
                        },
                        new
                        {
                            Id = 185,
                            AñoCursadoId = 17,
                            Eliminado = false,
                            Nombre = "Psicología y Educación"
                        },
                        new
                        {
                            Id = 186,
                            AñoCursadoId = 17,
                            Eliminado = false,
                            Nombre = "Pedagogia"
                        },
                        new
                        {
                            Id = 187,
                            AñoCursadoId = 17,
                            Eliminado = false,
                            Nombre = "Sociología de la Educación"
                        },
                        new
                        {
                            Id = 188,
                            AñoCursadoId = 17,
                            Eliminado = false,
                            Nombre = "Historia Argentina y Latinoamericana(1º cuatr.)"
                        },
                        new
                        {
                            Id = 189,
                            AñoCursadoId = 17,
                            Eliminado = false,
                            Nombre = "Movimiento y Cuerpo I"
                        },
                        new
                        {
                            Id = 190,
                            AñoCursadoId = 17,
                            Eliminado = false,
                            Nombre = "Taller de Práctica I"
                        },
                        new
                        {
                            Id = 191,
                            AñoCursadoId = 17,
                            Eliminado = false,
                            Nombre = "Problemáticas Contemporáneas de la Educación Inicial I"
                        },
                        new
                        {
                            Id = 192,
                            AñoCursadoId = 17,
                            Eliminado = false,
                            Nombre = "Comunicación y Expresión Oral y Esctrita"
                        },
                        new
                        {
                            Id = 193,
                            AñoCursadoId = 17,
                            Eliminado = false,
                            Nombre = "Resolución de Problemas y Creatividad (1º cuatr.)"
                        },
                        new
                        {
                            Id = 194,
                            AñoCursadoId = 17,
                            Eliminado = false,
                            Nombre = "Ambiente y Sociedad (2º cuatr.)"
                        },
                        new
                        {
                            Id = 195,
                            AñoCursadoId = 17,
                            Eliminado = false,
                            Nombre = "Área Estético-Expresiva I"
                        },
                        new
                        {
                            Id = 196,
                            AñoCursadoId = 17,
                            Eliminado = false,
                            Nombre = "Itinerarios por el Mundo de la Cultura"
                        },
                        new
                        {
                            Id = 197,
                            AñoCursadoId = 17,
                            Eliminado = false,
                            Nombre = "Producción Pedagógica"
                        },
                        new
                        {
                            Id = 198,
                            AñoCursadoId = 18,
                            Eliminado = false,
                            Nombre = "Didáctica General"
                        },
                        new
                        {
                            Id = 199,
                            AñoCursadoId = 18,
                            Eliminado = false,
                            Nombre = "Filosofía de la Educación (1º cuatr.)"
                        },
                        new
                        {
                            Id = 200,
                            AñoCursadoId = 18,
                            Eliminado = false,
                            Nombre = "Conocimiento y Educación (2º cuatr.)"
                        },
                        new
                        {
                            Id = 201,
                            AñoCursadoId = 18,
                            Eliminado = false,
                            Nombre = "Movimiento y Cuerpo II"
                        },
                        new
                        {
                            Id = 202,
                            AñoCursadoId = 18,
                            Eliminado = false,
                            Nombre = "Taller de Práctica II: Seminario de lo Grupal y los Grupos de Aprendizaje"
                        },
                        new
                        {
                            Id = 203,
                            AñoCursadoId = 18,
                            Eliminado = false,
                            Nombre = "Sujeto de la Educación Inicial"
                        },
                        new
                        {
                            Id = 204,
                            AñoCursadoId = 18,
                            Eliminado = false,
                            Nombre = "Didáctica de Educación Inicial I"
                        },
                        new
                        {
                            Id = 205,
                            AñoCursadoId = 18,
                            Eliminado = false,
                            Nombre = "Matemática y su Didáctica I"
                        },
                        new
                        {
                            Id = 206,
                            AñoCursadoId = 18,
                            Eliminado = false,
                            Nombre = "Literatura y su Didáctica"
                        },
                        new
                        {
                            Id = 207,
                            AñoCursadoId = 18,
                            Eliminado = false,
                            Nombre = "Ciencias Naturales y su Didáctica"
                        },
                        new
                        {
                            Id = 208,
                            AñoCursadoId = 18,
                            Eliminado = false,
                            Nombre = "Itinerarios por el Mundo de la Cultura"
                        },
                        new
                        {
                            Id = 209,
                            AñoCursadoId = 18,
                            Eliminado = false,
                            Nombre = "Producción Pedagógica"
                        },
                        new
                        {
                            Id = 210,
                            AñoCursadoId = 19,
                            Eliminado = false,
                            Nombre = "Tecnologías de la Información y de la Comunicación"
                        },
                        new
                        {
                            Id = 211,
                            AñoCursadoId = 19,
                            Eliminado = false,
                            Nombre = "Historia Social de la Educación y Política Educativa Argentina"
                        },
                        new
                        {
                            Id = 212,
                            AñoCursadoId = 19,
                            Eliminado = false,
                            Nombre = "Trayecto de Práctica III: Seminario de Instituciones Educativas"
                        },
                        new
                        {
                            Id = 213,
                            AñoCursadoId = 19,
                            Eliminado = false,
                            Nombre = "Matemática y su Didáctica II"
                        },
                        new
                        {
                            Id = 214,
                            AñoCursadoId = 19,
                            Eliminado = false,
                            Nombre = "Lengua y su Didáctica (1º cuatr.)"
                        },
                        new
                        {
                            Id = 215,
                            AñoCursadoId = 19,
                            Eliminado = false,
                            Nombre = "Alfabetización Inicial (2º cuatr.)"
                        },
                        new
                        {
                            Id = 216,
                            AñoCursadoId = 19,
                            Eliminado = false,
                            Nombre = "Ciencias Sociales y su Didáctica"
                        },
                        new
                        {
                            Id = 217,
                            AñoCursadoId = 19,
                            Eliminado = false,
                            Nombre = "Área Estético-Expresiva II"
                        },
                        new
                        {
                            Id = 218,
                            AñoCursadoId = 19,
                            Eliminado = false,
                            Nombre = "Problemáticas Contemporáneas de la Educación Inicial II (1º cuatr.)"
                        },
                        new
                        {
                            Id = 219,
                            AñoCursadoId = 19,
                            Eliminado = false,
                            Nombre = "Didáctica de la Educación Inicial II (2º cuatr.)"
                        },
                        new
                        {
                            Id = 220,
                            AñoCursadoId = 19,
                            Eliminado = false,
                            Nombre = "Espacios de Definición Institucional (1º cuatr.)"
                        },
                        new
                        {
                            Id = 221,
                            AñoCursadoId = 19,
                            Eliminado = false,
                            Nombre = "Espacios de Definición Institucional (2º cuatr.)"
                        },
                        new
                        {
                            Id = 222,
                            AñoCursadoId = 19,
                            Eliminado = false,
                            Nombre = "Itinerarios por el Mundo de la Cultura"
                        },
                        new
                        {
                            Id = 223,
                            AñoCursadoId = 19,
                            Eliminado = false,
                            Nombre = "Producción Pedagógica"
                        },
                        new
                        {
                            Id = 224,
                            AñoCursadoId = 20,
                            Eliminado = false,
                            Nombre = "Ética, Trabajo Docente, Derechos Humanos y Ciudadanos"
                        },
                        new
                        {
                            Id = 225,
                            AñoCursadoId = 20,
                            Eliminado = false,
                            Nombre = "Taller de Práctica IV"
                        },
                        new
                        {
                            Id = 226,
                            AñoCursadoId = 20,
                            Eliminado = false,
                            Nombre = "Ateneo: (Matemática- Ambiente y Sociedad (Ciencias Naturales- Ciencias Sociales) Lengua y Literatura- Formación Ètica y Ciudadana)"
                        },
                        new
                        {
                            Id = 227,
                            AñoCursadoId = 20,
                            Eliminado = false,
                            Nombre = "Sexualidad Humana y Educación  (1º cuatr.)"
                        },
                        new
                        {
                            Id = 228,
                            AñoCursadoId = 20,
                            Eliminado = false,
                            Nombre = "Itinerarios por el Mundo de la Cultura"
                        },
                        new
                        {
                            Id = 229,
                            AñoCursadoId = 20,
                            Eliminado = false,
                            Nombre = "Producción Pedagógica"
                        },
                        new
                        {
                            Id = 230,
                            AñoCursadoId = 21,
                            Eliminado = false,
                            Nombre = "Pedagogía"
                        },
                        new
                        {
                            Id = 231,
                            AñoCursadoId = 21,
                            Eliminado = false,
                            Nombre = "UCCV Sociología"
                        },
                        new
                        {
                            Id = 232,
                            AñoCursadoId = 21,
                            Eliminado = false,
                            Nombre = "Administración General"
                        },
                        new
                        {
                            Id = 233,
                            AñoCursadoId = 21,
                            Eliminado = false,
                            Nombre = "Economía I"
                        },
                        new
                        {
                            Id = 234,
                            AñoCursadoId = 21,
                            Eliminado = false,
                            Nombre = "Geografía Económica"
                        },
                        new
                        {
                            Id = 235,
                            AñoCursadoId = 21,
                            Eliminado = false,
                            Nombre = "Historia Económica"
                        },
                        new
                        {
                            Id = 236,
                            AñoCursadoId = 21,
                            Eliminado = false,
                            Nombre = "Construcción de Ciudadanía"
                        },
                        new
                        {
                            Id = 237,
                            AñoCursadoId = 21,
                            Eliminado = false,
                            Nombre = "Sistema de Información Contable I"
                        },
                        new
                        {
                            Id = 238,
                            AñoCursadoId = 21,
                            Eliminado = false,
                            Nombre = "Administración General"
                        },
                        new
                        {
                            Id = 239,
                            AñoCursadoId = 21,
                            Eliminado = false,
                            Nombre = "Matemática"
                        },
                        new
                        {
                            Id = 240,
                            AñoCursadoId = 21,
                            Eliminado = false,
                            Nombre = "Práctica Docente I"
                        },
                        new
                        {
                            Id = 241,
                            AñoCursadoId = 22,
                            Eliminado = false,
                            Nombre = "Instituciones Educativas"
                        },
                        new
                        {
                            Id = 242,
                            AñoCursadoId = 22,
                            Eliminado = false,
                            Nombre = "Didáctica y Curriculum"
                        },
                        new
                        {
                            Id = 243,
                            AñoCursadoId = 22,
                            Eliminado = false,
                            Nombre = "Psicología y Educación"
                        },
                        new
                        {
                            Id = 244,
                            AñoCursadoId = 22,
                            Eliminado = false,
                            Nombre = "Economía II"
                        },
                        new
                        {
                            Id = 245,
                            AñoCursadoId = 22,
                            Eliminado = false,
                            Nombre = "Sistema de Información Contable II"
                        },
                        new
                        {
                            Id = 246,
                            AñoCursadoId = 22,
                            Eliminado = false,
                            Nombre = "Derecho I"
                        },
                        new
                        {
                            Id = 247,
                            AñoCursadoId = 22,
                            Eliminado = false,
                            Nombre = "Economía"
                        },
                        new
                        {
                            Id = 248,
                            AñoCursadoId = 22,
                            Eliminado = false,
                            Nombre = "Estadística Aplicada"
                        },
                        new
                        {
                            Id = 249,
                            AñoCursadoId = 22,
                            Eliminado = false,
                            Nombre = "Didáctica de la Economía I"
                        },
                        new
                        {
                            Id = 250,
                            AñoCursadoId = 22,
                            Eliminado = false,
                            Nombre = "Práctica Docencia II"
                        },
                        new
                        {
                            Id = 251,
                            AñoCursadoId = 23,
                            Eliminado = false,
                            Nombre = "Historia y Política de la Educación Argentina"
                        },
                        new
                        {
                            Id = 252,
                            AñoCursadoId = 23,
                            Eliminado = false,
                            Nombre = "Filosofía"
                        },
                        new
                        {
                            Id = 253,
                            AñoCursadoId = 23,
                            Eliminado = false,
                            Nombre = "Metodología de la Investigación"
                        },
                        new
                        {
                            Id = 254,
                            AñoCursadoId = 23,
                            Eliminado = false,
                            Nombre = "Economía III"
                        },
                        new
                        {
                            Id = 255,
                            AñoCursadoId = 23,
                            Eliminado = false,
                            Nombre = "Finanzas Públicas"
                        },
                        new
                        {
                            Id = 256,
                            AñoCursadoId = 23,
                            Eliminado = false,
                            Nombre = "Derecho II"
                        },
                        new
                        {
                            Id = 257,
                            AñoCursadoId = 23,
                            Eliminado = false,
                            Nombre = "Sujetos de la Educación Secundaria "
                        },
                        new
                        {
                            Id = 258,
                            AñoCursadoId = 23,
                            Eliminado = false,
                            Nombre = "Práctica Docente III"
                        },
                        new
                        {
                            Id = 259,
                            AñoCursadoId = 23,
                            Eliminado = false,
                            Nombre = "Producción de los Recursos Didácticos I"
                        },
                        new
                        {
                            Id = 260,
                            AñoCursadoId = 24,
                            Eliminado = false,
                            Nombre = "Ética y Trabajo Docente"
                        },
                        new
                        {
                            Id = 261,
                            AñoCursadoId = 24,
                            Eliminado = false,
                            Nombre = "Educación Sexual Integral"
                        },
                        new
                        {
                            Id = 262,
                            AñoCursadoId = 24,
                            Eliminado = false,
                            Nombre = "UCCV Comunicación Social"
                        },
                        new
                        {
                            Id = 263,
                            AñoCursadoId = 24,
                            Eliminado = false,
                            Nombre = "Economía Social y Sostenible"
                        },
                        new
                        {
                            Id = 264,
                            AñoCursadoId = 24,
                            Eliminado = false,
                            Nombre = "Economía Argentina Latinoamericana e Internacional"
                        },
                        new
                        {
                            Id = 265,
                            AñoCursadoId = 24,
                            Eliminado = false,
                            Nombre = "Prácticas de Investigación"
                        },
                        new
                        {
                            Id = 266,
                            AñoCursadoId = 24,
                            Eliminado = false,
                            Nombre = "Práctica Docente IV (Residencia)"
                        },
                        new
                        {
                            Id = 267,
                            AñoCursadoId = 24,
                            Eliminado = false,
                            Nombre = "Producción de los Recursos Didácticos II"
                        },
                        new
                        {
                            Id = 268,
                            AñoCursadoId = 24,
                            Eliminado = false,
                            Nombre = "Unidad de Definición Institucional"
                        });
                });

            modelBuilder.Entity("InscripcionWeb.Models.AñoCursado", b =>
                {
                    b.HasOne("InscripcionWeb.Models.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InscripcionWeb.Models.DetalleAlumnoCarrera", b =>
                {
                    b.HasOne("InscripcionWeb.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InscripcionWeb.Models.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InscripcionWeb.Models.DetalleAlumnoMateria", b =>
                {
                    b.HasOne("InscripcionWeb.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InscripcionWeb.Models.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InscripcionWeb.Models.Materia", b =>
                {
                    b.HasOne("InscripcionWeb.Models.AñoCursado", "AñoCursado")
                        .WithMany()
                        .HasForeignKey("AñoCursadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
